default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: inventorydemo_development

test:
  <<: *default
  database: inventorydemo_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
